name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build
      run: docker build -t ghcr.io/ducc/thingy:$GITHUB_SHA -t ghcr.io/ducc/thingy:latest  -f Dockerfile .

    - name: Docker login
      if: github.ref == 'refs/heads/master'
      run: echo ${{ secrets.PACKAGES_ACCESS_TOKEN }} | docker login ghcr.io -u ducc --password-stdin

    - name: Push sha
      if: github.ref == 'refs/heads/master'
      run: docker push ghcr.io/ducc/thingy:$GITHUB_SHA 

    - name: Push latest
      if: github.ref == 'refs/heads/master'
      run: docker push ghcr.io/ducc/thingy:latest
